### ISSUE TITLE
satelitte semantic maps

### ISSUE THREAD

**Issue by melhousni** [iandouglas96/cross_view_slam#1]
Hi. Awesome work, thank you for open sourcing it!
Would you mind explaining how did you get the semantic labels for the google map images? Can you share the KITTI maps for training?
Thank you

**Comment by iandouglas96** [comment]
All of the map data is in the maps directory.  kitti0, morgantown, and ucity were labelled by hand, the svg files are there (open with inkscape, the labels are shapes you can delete if you just want the raw satellite image).  kitti2 and kitti9 were labelled automatically by a network trained on the other three, and the predicted labels are in the corresponding folders.

**Comment by melhousni** [comment]
Thanks for taking the time to explain. You mention that you trained an FCN to do the semantic segmentation. Can you point me toward which section in the code uses this FCN and its weights please?

**Comment by iandouglas96** [comment]
We only released the localization portion of the code, so the inference network is not in this repo.  However, it's just a plain FCN, nothing especially special, so it shouldn't be too complicated to implement and train one.

**Comment by melhousni** [comment]
Are the results reported in the paper from this code only or using the inferences from the trained FCNs?

**Comment by iandouglas96** [comment]
The results are from the maps in the maps directory, for which kitti2 an kitti9 were generated from the trained FCN

**Comment by melhousni** [comment]
Got it. Thank you
