### ISSUE TITLE
Which sequence of KITTI you choose in your example of README?

### ISSUE THREAD

**Issue by qiaozhijian** [iandouglas96/cross_view_slam#3]
Should I put sequence 00's labels into 2011_09_30_drive_0033_sync? or other sequence?
By the way, semantic kitti releases the labels of odometry. However, you use raw data. Is alignment done in your script?

**Comment by iandouglas96** [comment]
If you look at the KITTI odometry development kit from http://www.cvlibs.net/datasets/kitti/eval_odometry.php, there is a text file in there that tells you the mapping from sequence numbers to the raw data (pay attention, they don't always start exactly at the beginning).  While the point clouds in the odometry and raw datasets are slightly different formats, the semantic kitti labels work just fine.  The points are ordered the same.
