### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by qiaozhijian** [iandouglas96/cross_view_slam#4]
I am very appreciate for your work. 

I am very curious about how to project the 3D point cloud onto the satellite map in your video?
 
In addition, did you use rviz during your research? If so, can you provide your rviz configuration file?

**Comment by iandouglas96** [comment]
I used rviz and this package: https://github.com/lucasw/rviz_textured_quads to display the map inside rviz.  We do not release the LiDAR SLAM (UPSLAM) portion of our code, so my rviz config file would not be relevant, but feel free to apply, say, LeGO-LOAM and adapt accordingly.
