### ISSUE TITLE
Unable to get any meaningful output

### ISSUE THREAD

**Issue by Mnzs1701** [iandouglas96/cross_view_slam#5]
Thank you for open sourcing your amazing work, I was trying to implement the algorithm on the provided ucity and morgantown datasets on Ubuntu 20, ROS Noetic, the package compiles without any errors however there is nothing visible on rviz even after cycling through the entire rosbag.

The terminal shows the following output:
```
[ INFO] [1669884020.240457438]: No cache found, Loading vector map /home/user/cross_view_ws/src/cross_view_slam/maps/ucity.svg
[ INFO] [1669884020.274196317]: Map loaded.
[ INFO] [1669884020.274230856]: Size: 2064 x 1056
[ INFO] [1669884020.274264123]: Rasterizing map...
[ INFO] [1669884020.290079826]: Rasterized map size: 2064 x 1056
[ INFO] [1669884020.290180726]: maps generated
[ INFO] [1669884020.533160155]: transforming coord
[ INFO] [1669884022.705918658]: coord rotated
```

Both the topics
```
/cross_view_slam/scan
/cross_view_slam/map
```
Don't seem to be publishing anything.

There are no errors thrown by the program during compilation or while running. And the topic `/lidar_rgb_calib/painted_pc` shows the following output:
![Screenshot from 2022-12-01 15-38-56](https://user-images.githubusercontent.com/43721824/205025341-2ffe4c45-6abf-459a-a3b5-567803cbec0e.png)

Am I missing something here?

**Comment by iandouglas96** [comment]
The initialization sequence takes a while, at least a couple minutes on even a desktop machine.  You need to wait until `setup complete` is printed in terminal before you start playing the bag.

**Comment by Mnzs1701** [comment]
Thank you for your quick response, the `setup complete` occurred after about 30 minutes on my system  (`Intel® Core™ i7-9700 CPU @ 3.00GHz × 8` with  a `GeForce RTX 2080 Ti` GPU).
After caching this data the `setup complete` occurs almost instantly however the particles don't seem to converge even after completely cycling through the rosbag. The average time for the `filter update` is between `12000 ms - 38000 ms`
```
[ INFO] [1669957566.760046835]: scale uncertainty: 7.47006e-09
[ INFO] [1669957566.760076316]: scale: 1.31009
[ INFO] [1669957566.760605414]: pc cb
[ INFO] [1669957566.760630861]: Starting render
[ INFO] [1669957566.782276173]: Render took 21 ms
[ INFO] [1669957591.583192924]: particle weights: 1.00001
[ INFO] [1669957591.583776722]: particle reweighting complete
[ INFO] [1669957591.583848062]: 20000 particles
[ INFO] [1669957600.656194187]: Filter update 33873 ms
[ INFO] [1669957600.656438967]: -0.0970383
-0.0169849, 0.000238122
```
Is there something going wrong with the semantic segmentation? Attached is a screenshot of RViz
![Screenshot from 2022-12-02 10-53-26](https://user-images.githubusercontent.com/43721824/205221247-f51cc6e9-f760-4e13-94e2-6bd49dbb3728.png)

**Comment by iandouglas96** [comment]
You have probably not compiled in release mode.  See https://answers.ros.org/question/310112/equivalent-of-catkin_make-dcmake_build_typerelease-with-catkin-build/

**Comment by Mnzs1701** [comment]
Thank you, compiling with release mode did the trick. Filter update now happens in `2ms`
```
[ INFO] [1669962402.721221899]: scale uncertainty: 9.1824e-13
[ INFO] [1669962402.721258401]: scale: 1.31
[ INFO] [1669962402.768660936]: pc cb
[ INFO] [1669962402.768709731]: Starting render
[ INFO] [1669962402.775652024]: Render took 6 ms
[ INFO] [1669962402.777628715]: particle weights: 303.815
[ INFO] [1669962402.777657438]: particle reweighting complete
[ INFO] [1669962402.777673008]: 105 particles
[ INFO] [1669962402.777696397]: Filter update 2 ms
[ INFO] [1669962402.777720940]:  -0.789841
-0.0430946, -0.000576481
```
The particle filter converges quickly (in about 50 seconds). Thanks again for the assistance, I am closing the issue.
